### ISSUE TITLE
Suggestion: list saved portfolios on page

### ISSUE THREAD

**Issue by jjt** [AlexisDeschamps/portfolio-rebalancer#1]
I saved my portfolio and when presented with this blank page I thought it was lost, before clicking on the search field. Might be a good idea to list at least saved portfolios without having to click on the search field.

![image](https://cloud.githubusercontent.com/assets/399469/24372731/c6bde0ca-12e3-11e7-95bd-ce379cf73d8f.png)

**Comment by AlexisDeschamps** [comment]
Thanks for the suggestion! That seems like a good idea, since anyone who comes back is probably going to want to select one of their saved portfolios.

What do you think about having the drop-down open on page load even if the user does not have any saved portfolios? It might be slightly overwhelming, but right now I fear it may be kind of hard to know that you're supposed to click the text field.

**Comment by jjt** [comment]
Np! Good tool so far btw.

Yeah, you might want to have a few examples that a user could click on rather than the whole dropdown. That way you improve discovery without overwhelming them.

**Comment by AlexisDeschamps** [comment]
AutoComplete dropdown menu now opens by default if there is no portfolio already selected. Closing the issue. Thanks for the suggestion.
